### ISSUE TITLE
Command to alter book signature for lore purposes

### ISSUE THREAD

**Issue by Hoi15A** [Hoi15A/TBDUtils#9]
Should be clear that the command was used (e.g. with colouring) to prevent forged books.

Also add a string nbt entry of the name of the person that last altered the book (should not be visible in the lore of the book, just with the data command)

**Comment by ByrtZ** [comment]
Written books can now be altered by holding a written book in your main hand and executing /modifyauthor <newAuthor> in game. Your book will be replaced with a new written book with the author specified and an extra line of lore is added to indicate this is modified. An extra NBT tag, 'originalAuthor' is added onto modified written books with the name of the original book author.
